### ISSUE TITLE
Do you know why Unity 5.2.4f1 isn't opened exactly?

### ISSUE THREAD

**Issue by dmc31a42** [nesrak1/AssetsTools.NET#10]
I made bug fix for Unity 5.2.4f1, but I don't know why it should be.
I test Detention(5.2.4f1) and testing samples(I built cotaining zero, one two and three asset)
Maybe this does not effect other version
8b006648cf3e1003e9783287c866d7619b474132

**Comment by nesrak1** [comment]
I didn't add the library for 5.4 and under. Where is it erroring at?

**Comment by nesrak1** [comment]
Closing because 5.4 and below was added. Reading seems fine but if you have problems with writing let me know.
