### ISSUE TITLE
How do I modify the data inside a MonoBehaviour?

### ISSUE THREAD

**Issue by nsunh** [nesrak1/AssetsTools.NET#101]
![image](https://user-images.githubusercontent.com/128416267/229333495-6d640ab2-e1b6-4082-a30f-a80a4f8cd560.png)
I want to change the data values in the blue part.
I've tried various methods, but haven't found a way to access that field.
Can you help me with this?

**Comment by nsunh** [comment]
I used GetChildrenList(), but it didn't work at all. Do I need to approach data of type Array differently?

**Comment by nesrak1** [comment]
Set just the first value:
AT2: `baseField["tips"]["Array"][0].GetValue().Set(someValue)`
AT3: `baseField["tips.Array"][0].AsString = someValue`

Iterate all values in the array:
AT2: `foreach (var data in baseField["tips"]["Array"].GetChildrenList())`
AT3: `foreach (var data in baseField["tips.Array"])`

**Comment by nsunh** [comment]
![image](https://user-images.githubusercontent.com/128416267/229386501-e544ce78-2a11-4c53-8aac-606670ab36b9.png)
![image](https://user-images.githubusercontent.com/128416267/229386527-20fa19a8-e22f-4948-afc4-e4a6501ec4f1.png)
![image](https://user-images.githubusercontent.com/128416267/229386554-d9a87d99-a111-4e29-9642-9930735ea191.png)
Thank you so much for your quick response.
However, I have encountered the following problem
I apologize for bothering you, but is there any way to resolve this?
I am using the latest version of AssetsTool.net.

**Comment by nesrak1** [comment]
You're trying to read/write a MonoBehaviour in AT2, so you need to do a little bit of extra code for it instead of just doing `GetTypeInstance(...).GetBaseField()`. Information about that is at https://github.com/nesrak1/AssetsTools.NET#reading-a-monobehaviour in the readme.

**Comment by nsunh** [comment]
Thank you for your help. I'll fix it and share the results:)

**Comment by nsunh** [comment]
Thanks again for your help. I feel very fortunate to have gotten such an immediate response.
I can see how much you care about your project.
But because of my inexperience, I'm stuck again.
-----------------------------------------------
using AssetsTools.NET.Extra;
using AssetsTools.NET;
using AssetsTools;
using System.IO;

var am = new AssetsManager();
var inst = am.LoadAssetsFile("C:\\Program Files (x86)\\Steam\\steamapps\\common\\Dinkum\\Dinkum_Data\\level0", true);
//call am, load file
am.LoadClassPackage("C:\\Users\\nsunh\\source\\repos\\DinkumKR\\DinkumKR\\lib\\classdata.tpk");
am.LoadClassDatabaseFromPackage(inst.file.typeTree.unityVersion);
//load classdata
var lScreenObjInf = inst.table.GetAssetInfo("LoadingScreenImageAndTips");
var lScreenObjBf = am.GetTypeInstance(inst, lScreenObjInf).GetBaseField();
var lScreenCompArr = lScreenObjBf.Get("m_Component").Get("Array");
//set Inf, Bf, Arr of GameObj
AssetFileInfoEx monoBehaviourInf = null;
AssetTypeValueField monoBehaviourBf = null;
//set inf, Bf of mono
for (var i = 0; i < lScreenCompArr.GetChildrenCount(); i++)
{
    //get comp inf (but don't deserialize yet)
    var childPtr = lScreenCompArr[i].Get("component");
    var childExt = am.GetExtAsset(inst, childPtr, true);
    var childInf = childExt.info;

    //skip if not MonoBehaviour
    if (childInf.curFileType != (uint)AssetClassID.MonoBehaviour)
        continue;

    //check the MonoScript for its class name

    //deserialize the MonoBehaviour asset
    childExt = am.GetExtAsset(inst, lScreenCompArr[i], false);
    var childBf = childExt.instance.GetBaseField();
    var monoScriptPtr = childBf.Get("m_Script");

    //get MonoScript from MonoBehaviour
    var monoScriptExt = am.GetExtAsset(childExt.file, monoScriptPtr);
    var monoScriptBf = monoScriptExt.instance.GetBaseField();

    var className = monoScriptBf.Get("m_ClassName").GetValue().AsString();
    if (className == "LoadingScreenImageAndTips")
    {
        //we found the script, now we can edit it
        monoBehaviourInf = childInf;
        monoBehaviourBf = childBf;
        break;
    }
}
if (monoBehaviourInf == null)
    throw new Exception("couldn't find Script on this GameObj");

////load MonoBehaviour fields on top of regular fields
var managedFolder = Path.Combine(Path.GetDirectoryName(inst.path), "Managed");
monoBehaviourBf = MonoDeserializer.GetMonoBaseField(am, inst, monoBehaviourInf, managedFolder);

//change mono field
monoBehaviourBf["tips"]["Array"][0].GetValue().Set("Thank you!");

var newMonoBytes = monoBehaviourBf.WriteToByteArray();
var repl = new AssetsReplacerFromMemory(
    0, monoBehaviourInf.index, (int)monoBehaviourInf.curFileType,
    AssetHelper.GetScriptIndex(inst.file, monoBehaviourInf),
    newMonoBytes
);

using (var stream = File.OpenWrite("resources-modified.assets"))
using (var writer = new AssetsFileWriter(stream))
{
    inst.file.Write(writer, 0, new List<AssetsReplacer>() { repl }, 0);
}

am.UnloadAllAssetsFiles();
-------------------------------------
Here's the full code I used.
When I built this code, I encountered the following problem.
![image](https://user-images.githubusercontent.com/128416267/229546469-500f91c0-4310-4c81-a247-6004858682fb.png)

So, I made the following changes to my code and built it.
![image](https://user-images.githubusercontent.com/128416267/229547030-323be8f1-24f7-4316-a88d-65ffa0201b7d.png)

I don't know if this is the right way to do it, but I ran into the following problem before I could confirm that it worked.
![image](https://user-images.githubusercontent.com/128416267/229547946-c95e9eb3-b435-4280-9ee7-c89b12c272a5.png)

//The structure of the game object.
![image](https://user-images.githubusercontent.com/128416267/229548374-e83b8732-c013-4aea-8173-9c241319ee7c.png)
//first try
![image](https://user-images.githubusercontent.com/128416267/229549084-e21a7b85-18e7-406a-9489-13972766c11c.png)
//second
![image](https://user-images.githubusercontent.com/128416267/229548694-22820b22-3cba-499f-8e16-c67252de86a7.png)

**Comment by nesrak1** [comment]
I forgot that the game has to use IL2CPP (it's a switch game), but only mono games are supported in AT2. AT3 supports IL2CPP with CPP2IL. You can get AT3 by building the `upd21-with-inst` branch or by installing the preview package on nuget. The documentation moved to the wiki for AT3: https://github.com/nesrak1/AssetsTools.NET/wiki/Getting-Started:-MonoBehaviour-reading

**Comment by nsunh** [comment]
Thank you for your kind response! I'll give AT3 a try :)

**Comment by nsunh** [comment]
![image](https://user-images.githubusercontent.com/128416267/229693260-7c502d29-dccd-4872-9772-1d018c546a38.png)
Thanks to you, we've solved it, and I'm so happy.
Finally, I have one question.
I used PathID to get the basefield.
![image](https://user-images.githubusercontent.com/128416267/229693859-059e764e-7cf0-4ee0-8b34-a6d62b40d015.png)
However, when the version is updated, the pathID will also change, so I'm wondering if it's possible to get the basdfield by name like in AT2.
If not, should I write something like this?
--------------------------------------------------
foreach (var goInfo in afile.GetAssetsOfType(AssetClassID.MonoBehaviour))
{
    var goBase = manager.GetBaseField(afileInst, goInfo);
    if (goBase["m_Name"].AsString == "monoName")
    {
        ...
    }
}
---------------------------------------------------------------

**Comment by nsunh** [comment]
![image](https://user-images.githubusercontent.com/128416267/229993103-5f4cfe87-a374-4fff-9caa-68680d72c890.png)
The mono doesn't have a name value, so I worked around it this way. I don't know if this is correct, but it works. Thanks for the help in the meantime :)
