### ISSUE TITLE
Hello, can AsseTools replace fonts?

### ISSUE THREAD

**Issue by yeooii** [nesrak1/AssetsTools.NET#103]
Hello, can AsseTools replace fonts?

**Comment by nesrak1** [comment]
You can look at the code used in UABEA: https://github.com/nesrak1/UABEA/blob/master/FontPlugin/Program.cs

It only edits font assets that use ttf/otf and does not edit any font atlas images.

**Comment by yeooii** [comment]
Okay, thank you very much.

**Comment by yeooii** [comment]
Hello, I failed to modify it using https://github. com/nesrak1/UABEA/blob/master/FontPlugin/Program.cs. I am using the upd21 with inst branch.

**Comment by yeooii** [comment]
![image](https://user-images.githubusercontent.com/96559248/233950761-9fb9f91b-ef16-41a9-be59-add67a2f1acf.png)
I have tried both of the settings in the red box above, but both have failed. And even if the above line of code (set the length of Children to 0) is removed, it will still fail.

**Comment by nesrak1** [comment]
You need to "fix" the Font asset so that it uses a byte array.

https://github.com/nesrak1/UABEA/blob/master/FontPlugin/Program.cs#L17

**Comment by yeooii** [comment]
Thank you for replying to me. I resolved this issue by generating a List<AssetTypeValueField>() for my Font. ttf myself. Thank you very much.
