### ISSUE TITLE
About AT3 NewReplacer 

### ISSUE THREAD

**Issue by liuxinyumocn** [nesrak1/AssetsTools.NET#115]
Hello author, I'm really looking forward to using AT3. While reading the wiki during the process, I found that some classes don't match completely. Could you please let me know if AssetTools.NET/Standard/NewReplacer provides relevant usage methods? I'm looking forward to your reply.

**Comment by nesrak1** [comment]
I will update the wiki soon but you can find the hello world example here: https://github.com/nesrak1/AssetsTools.NET/blob/9fd593ac7ed818ba99332d5097f500b0bbceb3f9/HelloWorld/Program.cs

**Comment by liuxinyumocn** [comment]
Thank you very much!
By the way, I discovered a new issue while using writer. My original ab file size is about 6kb, and when I modify the name of one of the texture resources and save it, the modified ab file size is about 13kb.This leads to greater download overhead.May I ask how to solve it?

**Comment by nesrak1** [comment]
Note: I updated the wiki earlier so it should be up to date if you need to reference anything more complicated.

> By the way, I discovered a new issue while using writer. My original ab file size is about 6kb, and when I modify the name of one of the texture resources and save it, the modified ab file size is about 13kb.This leads to greater download overhead.May I ask how to solve it?

It sounds like you had a bundle that was originally compressed, but you didn't recompress it when you were finished. The wiki has a section on this: https://github.com/nesrak1/AssetsTools.NET/wiki/Getting-Started%3A-Bundle-file-writing/_edit#compressing-the-bundle

**Comment by liuxinyumocn** [comment]
It's work! Thanks.
Looking forward to the release version.
