### ISSUE TITLE
[DOCS] Wrong link to .tpk file

### ISSUE THREAD

**Issue by Albeoris** [nesrak1/AssetsTools.NET#122]
There is the invalid [link](https://github.com/AssetRipper/Tpk/actions/workflows/make_tpk.yml) on this [page](https://github.com/nesrak1/AssetsTools.NET/wiki/Getting-Started:-Assets-file-reading) of documentation:

> You can grab a tpk here: https://github.com/AssetRipper/Tpk/actions/workflows/make_tpk.yml (do not use the brotli version.)

**Comment by nesrak1** [comment]
The link updated fairly recently (about a week ago). The new link is https://github.com/AssetRipper/Tpk/actions/workflows/type_tree_tpk.yml. I'll update it
