### ISSUE TITLE
Library doesn't work at all with error "System.IO.EndOfStreamException: 'Unable to read beyond the end of the stream.'"

### ISSUE THREAD

**Issue by neobenedict** [nesrak1/AssetsTools.NET#13]
edit: never mind, but the documentation should be updated, because this is invalid syntax:
```
var am = new AssetsManager();
var bun = am.LoadBundleFile("bundle.unity3d", true);
var firstAssetsFile = BundleHelper.LoadAssetFromBundle(bun, 0); //or use name instead
```

**Comment by nesrak1** [comment]
I believe LoadBundleFile no longer has a second argument. I'll try to fix that in a sec, thanks for catching that.

**Comment by neobenedict** [comment]
While you're here, any idea how to access the m_StreamData of a Texture2D so I can process it?

https://i.imgur.com/JYEi3Nu.png

What do I feed that archive:/ into to access it?

**Comment by nesrak1** [comment]
Use `LoadAssetDataFromBundle(AssetBundleFile bundle, string name)` to get just the data from a file in the bundle without trying to read it as an assets file. You'll need to get rid of the archive:/ part and possibly the folder path (so just the file name) for it to find it. Then just seek and take the amount of bytes as shown in the texture2d data.

**Comment by neobenedict** [comment]
That works, thanks.

**Comment by nesrak1** [comment]
Fixed readme, closing
