### ISSUE TITLE
BaseField does not contain a serializable field of ScriptableObject after update of game

### ISSUE THREAD

**Issue by Albeoris** [nesrak1/AssetsTools.NET#130]
This is ScriptableObject:

```csharp
	public class LanguageSourceAsset : ScriptableObject, ILanguageSource
	{
		[Token(Token = "0x4002FB8")]
		[FieldOffset(Offset = "0x18")]
		public LanguageSourceData mSource;
        }	
```

The field `mSource` is exists in the first version of the game, but is missing in the second, although the type description has not changed, and the contents of the file indicate that all data is serialized and in place (I look in HEX)

This is debug session from the previous version of a game:
![image](https://github.com/nesrak1/AssetsTools.NET/assets/4787832/7fee8b81-0179-433d-8bdf-dabb6daca528)

This is debug session from the newest version of a game:
![image](https://github.com/nesrak1/AssetsTools.NET/assets/4787832/b0b9d941-f8f1-42f9-8600-9a725984253b)

I've checked in various editors and resource viewers and none of them see this field. But it is there and is used correctly during the play. I don't see any significant differences in the file structure. Apparently the problem is with TypeTreeTpk.tpk or DummyDll.

What I need to do?

Both versions are attached:
[v1.zip](https://github.com/nesrak1/AssetsTools.NET/files/14001433/v1.zip)
[v2.zip](https://github.com/nesrak1/AssetsTools.NET/files/14001434/v2.zip)

The name of the object is `I2Languages` (`AssetClassID.MonoBehaviour`)

**Comment by nesrak1** [comment]
What is your code like? What method are you using to read the assemblies? Does this open in UABEA? I can't do much with only the information you've given me so far.

**Comment by Albeoris** [comment]
@nesrak1 

My code and method are here:
```
AssetsManager manager = new();
manager.LoadClassPackage($@"{rootPath}\TypeTreeTpk.tpk");
manager.MonoTempGenerator = new MonoCecilTempGenerator($@"{rootPath}\DummyDlls");

AssetsFileInstance? assetInstance = manager.LoadAssetsFile($@"{rootPath}\romfs\Data\sharedassets0.assets", true);
AssetsFile? assetsFile = assetInstance.file;
manager.LoadClassDatabaseFromPackage(assetsFile.Metadata.UnityVersion);

LanguageSourceAsset languagesObj = EnumerateMonoBehaviours(assetsFile, manager, assetInstance, "I2Languages").Single().CastTo<LanguageSourceAsset>();

        foreach (AssetFileInfo? obj in assetsFile.GetAssetsOfType(AssetClassID.MonoBehaviour))
        {
            AssetTypeValueField? goBase;
            try
            {
                goBase = manager.GetBaseField(assetInstance, obj);
            }
            catch (EndOfStreamException ex)
            {
                continue;
            }

            if (goBase["m_Name"].AsString == "I2Languages")
            {
                AssetTypeValueField? languages = goBase["mSource"];
                if (languages.FieldName == "DUMMY")
                    throw new Exception("Problem is here. :/");
            }
        }
```

> Does this open in UABEA?
As I said:

> I've checked in various editors and resource viewers and none of them see this field.

UABEA is included.

The main thing is that there are two versions of the game - before the patch and after the patch. Before the patch, I could find the required field, after the patch it is missing, although neither the file nor the type description have changed. Not a single editor sees this field either in the first version or in the second.

**Comment by Albeoris** [comment]
UABEA:
![image](https://github.com/nesrak1/AssetsTools.NET/assets/4787832/bab8f082-3db5-4664-8168-686a378c6a16)

**Comment by nesrak1** [comment]
Usually this kind of thing would be caused by whatever you used to convert il2cpp to dlls messing up, usually with attributes. Even more so since you said all of the other tools are having issues with it. You can step through the `GetAcceptableFields` method in `MonoCecilTempGenerator.cs` to see what conditions the `mSource` field is failing.

**Comment by Albeoris** [comment]
@nesrak1 , no problem is not related to `MonoCecilTempGenerator`

The game has been released in Steam as Demo:
https://store.steampowered.com/app/2865440/FRONT_MISSION_2_Remake/

And there is managed assemblies without IL2CPP.
`sharedassets0.assets` and `sharedassets0.resources` are packed in `data.unity3d` but correctly extracted by UABEA.
I found the resource again but the error is same:

mSource is correctly described as a part of `LanguageSourceAsset` and exists in binary data but not show as available property:
```csharp
	[CreateAssetMenu(fileName = "I2Languages", menuName = "I2 Localization/LanguageSource", order = 1)]
	public class LanguageSourceAsset : ScriptableObject, ILanguageSource
	{
		public LanguageSourceData mSource = new LanguageSourceData();
	}
	
        [ExecuteInEditMode]
	[Serializable]
	public class LanguageSourceData
	{
	}
```

![image](https://github.com/nesrak1/AssetsTools.NET/assets/4787832/333cc925-9f0b-4d6b-95e5-fe03d6ff9070)

**Comment by Albeoris** [comment]
Damn... if `MonoGenerator` is not specified it not loading script fileds?! X"D

**Comment by Albeoris** [comment]
![image](https://github.com/nesrak1/AssetsTools.NET/assets/4787832/5f317c8a-eb4e-4f42-b733-5918628f5610)
Yahooo!

To debug this we need to break on `GetTemplateBaseField`:
```csharp
if (typeId == 114 && this.MonoTempGenerator != null && !flag2 && reader != null)
      {
        AssetPPtr assetPptr = AssetPPtr.FromField(baseField.MakeValue(reader, absByteStart)["m_Script"]);
        if (!assetPptr.IsNull())
        {
          AssetsFileInstance assetsFileInstance = assetPptr.FileId != 0 ? inst.GetDependency(this, assetPptr.FileId - 1) : inst;
          if (assetsFileInstance == null)
            return baseField;
          Dictionary<long, AssetTypeTemplateField> dictionary = (Dictionary<long, AssetTypeTemplateField>) null;
          if (this.UseMonoTemplateFieldCache)
          {
            if (this.monoCldbTemplateFieldCache.TryGetValue(assetsFileInstance, out dictionary))
            {
              AssetTypeTemplateField templateBaseField;
              if (dictionary.TryGetValue(assetPptr.PathId, out templateBaseField))
                return templateBaseField;
            }
            else
              this.monoCldbTemplateFieldCache[assetsFileInstance] = dictionary = new Dictionary<long, AssetTypeTemplateField>();
          }
          AssetFileInfo assetInfo = assetsFileInstance.file.GetAssetInfo(assetPptr.PathId);
          long absoluteByteOffset = assetInfo.GetAbsoluteByteOffset(assetsFileInstance.file);
          int typeId1 = assetInfo.TypeId;
          ushort scriptIndex1 = assetsFileInstance.file.GetScriptIndex(assetInfo);
          string assemblyName;
          string nameSpace;
          string className;
          int num = this.GetMonoScriptInfo(assetsFileInstance, absoluteByteOffset, typeId1, scriptIndex1, out assemblyName, out nameSpace, out className, readFlags) ? 1 : 0;
          if (assemblyName.EndsWith(".dll"))
            assemblyName = assemblyName.Substring(0, assemblyName.Length - 4);
          if (num != 0)
          {
            AssetTypeReference key = new AssetTypeReference(className, nameSpace, assemblyName);
            AssetTypeTemplateField templateBaseField;
            if (this.UseMonoTemplateFieldCache && this.monoTemplateFieldCache.TryGetValue(key, out templateBaseField))
            {
              dictionary[assetPptr.PathId] = templateBaseField;
              return templateBaseField;
            }
            AssetTypeTemplateField templateField = this.MonoTempGenerator.GetTemplateField(baseField, assemblyName, nameSpace, className, new UnityVersion(file.Metadata.UnityVersion));
            if (templateField != null)
            {
              baseField = templateField;
              if (this.UseMonoTemplateFieldCache)
              {
                dictionary[assetPptr.PathId] = this.monoTemplateFieldCache[key] = baseField;
                return baseField;
              }
            }
          }
        }
      }
      ````
