### ISSUE TITLE
Editing / patching globalgamemanagers?

### ISSUE THREAD

**Issue by Raicuparta** [nesrak1/AssetsTools.NET#16]
I see that this tool lets you explore globalgamemanagers but doesn't let you edit it. UABE has this option to export these files to a text file, and then import it again as a way to create a modified version.

I'm actually looking for a way to edit globalgamemanagers programmatically. Just want to be able to go into it, change a setting in BuildSettings, and save a new file. Do you have any tips on how this could be achieved?

Sorry that this isn't an actual issue, I just didn't know any other way to contact you.

**Comment by Raicuparta** [comment]
Pinging @nesrak1 because I don't know if this would get a notification otherwise 😅

**Comment by nesrak1** [comment]
There's a writing code example in the readme here:

https://github.com/nesrak1/AssetsTools.NET/blob/master/README.md#assets-file-writing

If you need globalgamemanagers specific example, here's one from qmodmanager. But that version didn't have WriteToByteArray yet like in the above link:

https://github.com/SubnauticaModding/QModManager/blob/master/Executable/AudioFixer.cs

**Comment by Raicuparta** [comment]
Ah I didn't realize it would be the same as any other asset file. And you always need this `cldb.dat` file from UABE? No open source way to get the same result? 😕

**Comment by nesrak1** [comment]
Either an uncompressed cldb file or the classdatabase.tpk found in [any of the releases](https://github.com/nesrak1/AssetsTools.NET/releases) is needed (both come from uabe, sorry). If you don't want to use it there are two options:
1. Modify the bytes of the file manually to make your change. I don't think I have any utils for that so here's some sample code to do so:
```cs
var inf = inst.table.GetAssetInfo("SomeAsset");
var reader = inst.file.reader;
reader.BaseStream.Position = inf.absoluteFilePos;
var bytes = reader.ReadBytes((int)inf.curFileSize);
//do stuff with bytes, maybe use a memorystream/binarywriter
var repl = new AssetsReplacerFromMemory(0, inf.index, inf.curFileType, 0xFFFF, bytes);
var writer = new AssetsFileWriter(File.OpenWrite("file-modified.assets"));
inst.file.Write(writer, new AssetsReplacer[] { repl });
```
2. Make your own cldb file using type trees (uabe gets info through exe though, so it won't be exactly the same). I haven't released it because it's kind of out of date, but if you need it, there's a program that can generate cldb files using the type trees from bundles and project files. If you want to go down this route just tell me and I'll fix it.

**Comment by Raicuparta** [comment]
1. That's kinda of what I'm already doing, but it would basically stop working after every update, right? Since globalgamemanagers changes every time you build the game in Unity. What I did was change the file with UABE, then generate a binary diff, and use that diff to patch the original globalgamemanagers.

I tried doing `Options -> Edit Type Database` in UABE, but I need this cldb file, which I'm not sure how to get. I tried exporting the `tpk` file in  `Options -> Edit Type Package`, which results in a .dat file. But then if I open it in `Edit Type Database` it doesn't seem to be readable? Probably not at all what I'm supposed to do.
 
2. This seems more desirable. I would be interested in attempting this, unless my concerns with the binary format aren't valid.

**Comment by nesrak1** [comment]
> I tried doing Options -> Edit Type Database in UABE, but I need this cldb file, which I'm not sure how to get. I tried exporting the tpk file in Options -> Edit Type Package, which results in a .dat file. But then if I open it in Edit Type Database it doesn't seem to be readable? Probably not at all what I'm supposed to do.

If you're opening the tpk from my releases section (which is uncompressed), it comes out invalid in UABE. Not sure why, I should probably make an issue on UABE about that. Instead, just use the classdatabase.tpk in UABE itself.

> This seems more desirable. I would be interested in attempting this, unless my concerns with the binary format aren't valid.

Sure, I'll work on fixing up the program. Just a few notes:
a. Depending on which asset you are changing, it may not change very much or at all
b. You'll have to keep the file up to date yourself if the game updates, it won't do it for you

**Comment by Raicuparta** [comment]
> Sure, I'll work on fixing up the program. Just a few notes:
a. Depending on which asset you are changing, it may not change very much or at all

I'm only trying to change one small thing: in `globalgamemanagers > BuildSettings > enabledVRDevices`, by default it is an empty array. I want to change it to an array with one element, `"OpenVR"`.

I tried again with the UABE files and it works, yeah. I'll try to figure out how to do it this way, and see if it works with all versions we have so far.

> b. You'll have to keep the file up to date yourself if the game updates, it won't do it for you

Ah so there's really no point... I'm trying to make it so the patch works in future updates without intervention.

Be the way you have been super helpful, thanks for everything so far!

**Comment by nesrak1** [comment]
If you want to support all versions, I would just use the decompressed tpk file directly and have AssetsManager pick the right version. The only reason I suggested to use cldb is to view the format in UABE, but it's easier just to use the tpk.

**Comment by Raicuparta** [comment]
Understood. Thanks for all the help, I learned a lot.
