### ISSUE TITLE
One question

### ISSUE THREAD

**Issue by Igor55x** [nesrak1/AssetsTools.NET#23]
**Can you please give me a code to remove assets?**
I just don't understand how to do it and the readme file doesn't describe how to do it.

Can I somehow contact you so as not to create new **issues**?

**Comment by nesrak1** [comment]
If you have discord, my username is `nes#3391`.
For your question, you can just use an `AssetsRemover` instead of an `AssetsReplacerFromXXX`. The only field I believe you need to fill out is pathId and maybe classId.

**Comment by Igor55x** [comment]
Thanks for the reply.
