### ISSUE TITLE
Asset bundle data offset is increased by 16 bytes when writing

### ISSUE THREAD

**Issue by NoelTautges** [nesrak1/AssetsTools.NET#29]
When writing a file I read with AssetsManager, the offset of the asset data is increased from 0x1000 to 0x1010. I've tested it with Unity versions 2017.4.33f1 and 2018.4.26f1 and it uniformly increases the offset by 16 bytes. When replacing the original file, the mismatch causes Unity to hang with the following errors (the first probably being specific to the file):

```
Mismatched serialization in the builtin class 'PreloadData'. (Read 12 bytes but expected 144 bytes)
 
(Filename:  Line: 1929)

The file 'sharedassets0_original.assets' is corrupted! Remove it and launch unity again!
[Position out of bounds!]
 
(Filename:  Line: 215)
```

I isolated the mismatch to [if statement](https://github.com/nesrak1/AssetsTools.NET/commit/9d82959c0d5d112e77ff2455791a82dbeb132f7b#diff-efff435bc1dbc15d70950c4f19b7ab22fab3f9cfbc7cc79baf19f2ef27bb56f8L194) where after the method pads the file to 0x1000 bytes, it adds another 16 if the position is a multiple of 16. I've been removing the first case during development, but is there a way to make sure whatever bug got fixed stays fixed while eliminating the mismatch?

I have attached [the code I used to test the issue and the bundles used and produced](https://github.com/nesrak1/AssetsTools.NET/files/5825092/assets_write_test.zip). Thank you for making this project, it is very helpful!

**Comment by nesrak1** [comment]
Check and see if the latest commit fixes it. It should only align if padding isn't needed.

**Comment by NoelTautges** [comment]
All fixed. Thanks so much!
