### ISSUE TITLE
[Bug] Throw System.ArgumentOutOfRangeException in GetAssetNameFast when read '0x00000062 (DelayedCallManager)' in globalgamemanager

### ISSUE THREAD

**Issue by dmc31a42** [nesrak1/AssetsTools.NET#3]
Throw System.ArgumentOutOfRangeException in GetAssetNameFast when read '0x00000062 (DelayedCallManager)' in globalgamemanager, because 'DelayedCallManager' is unknown in UABE.Cpp also.( UABE.Cpp said 'Unknown asset format!' when 'View Data' DelayedCallManager Type asset in globalgamemanager.)
in classdatabase file, DelayedCallManager has only one field, so type.fields[1] is invaild.

https://github.com/nesrak1/AssetsTools.NET/blob/7bee484cd49d896dd01dd81e513d2089bd7b2416/UABE.NET/Winforms/AssetViewer.cs#L156-L157

![image](https://user-images.githubusercontent.com/13437953/38142969-66362c4a-3479-11e8-8469-36bd66887554.png)

I changed to
```C#
            if (type.fields.Count <= 1) return type.name.GetString(cldb);
            if (type.fields[1].fieldName.GetString(cldb) == "m_Name")
```

**Comment by nesrak1** [comment]
Yeah this is a weird thing I've noticed while writing my exporter and other classes like ParticleSystem don't work either. ReadAssetNameFast should probably use AssetExtra.HasName instead and then check for GameObject and Monobehaviour on the side. Other than that feel free to make a pr checking if the fieldCount > 0 (or just wait for me to do it in another bug fix commit in a couple days)

**Comment by dmc31a42** [comment]
If you think there is more efficient solution, then please reject pull request #4

**Comment by nesrak1** [comment]
Sorry fasthub was not showing the pull request on these so I thought it was an issue (sorry). There may be a more efficient way to do names though, so I will run tests and see if it improves anything. Uabe.net is definitely slower and I'm looking for ways to improve that load time.
