### ISSUE TITLE
OutOfMemoryException when trying to view BuildSettings

### ISSUE THREAD

**Issue by SFGrenade** [nesrak1/AssetsTools.NET#39]
Game: Hollow Knight
Version 1.5.68.11808
Unity Version used for it: 2020.2
AssetsView version: `AssetsTools Update 3`

Procedure:
1. Start AssetsView
2. File -> Add File (`globalgamemanagers`)
3. Double click `BuildSettings`
4. OoM exception

**Comment by SFGrenade** [comment]
i mean `AssetsTools Update 17 (2.0.8)`, my bad

**Comment by nesrak1** [comment]
thanks github

**Comment by SFGrenade** [comment]
my bad, sorry
