### ISSUE TITLE
Replacing assets not working correctly

### ISSUE THREAD

**Issue by Skyluker4** [nesrak1/AssetsTools.NET#40]
I'm trying to replace some assets in an asset bundle using a tool I made that runs on this library (https://github.com/Skyluker4/UnityAssetReplacer). When I save a new asset bundle to replace assets, something gets messed up. Without even actually replacing any assets and just making a copy of the bundle using AssetTools.NET it ends up being 20 bytes less than the original. The beginning of the file differs from the original (about the first few hundred bytes or so are different).

This is only for one specific asset bundle, other ones work fine. When trying to read from UABE, it says "invalid assets file".

Here's a look at the files -- the original on the left and the one AssetTools.NET generated on the right.

![image](https://user-images.githubusercontent.com/10624379/123173421-2fd0a680-d444-11eb-825e-7c070ac8d20d.png)

I don't know if this is a problem with my own code or a problem with the library. I'm using ```AssetReplacerFromMemory``` to replace the assets and ```BundleReplacerFromMemory``` and ```AssetsFileWriter``` to create the new bundle.

**Comment by nesrak1** [comment]
When writing, I only create one block whereas the file you have has three blocks. Since the file is decompressed, there shouldn't be any difference in the data, only the block table (which is 10 bytes each, 3*10-1*10=20 byte difference). Does this open in UABEA or only fail in UABE?

**Comment by Skyluker4** [comment]
It does not open in UABE, UABEA, or the game itself when imported. Here's a stack trace and the exception with UABEA:
![image](https://user-images.githubusercontent.com/10624379/123200608-adada580-d476-11eb-890a-087abb292a5b.png)

**Comment by nesrak1** [comment]
Only so much I can do without the file so I'll try to ask some questions to figure out what's going wrong.
1. If you write just the modified assets file without the bundle, can you still open it?
2. When you hit the exception, what is Type_0D's reader.Position value?
3. It shouldn't affect opening the file initially, but on this line
https://github.com/Skyluker4/UnityAssetReplacer/blob/main/UnityAssetReplacer/UnityAssetReplacer.cs#L75
you should replace `0xFFFF` with `AssetHelper.GetScriptIndex(_assetsFile.file, assetInfo);` if you're reading monobehaviours.

**Comment by Skyluker4** [comment]
1. I'll work on modifying my program to save just the assets file.
2. When it gets to the exception, ```reader.Position``` is ```0x55488``` in ```AssetsTools.NET.TypeTree.Read(AssetsTools.NET.AssetsFileReader reader, uint version)```, which is also the exact value of ```reader._stream._capacity``` and length of ```reader._stream._buffer```. 
3. Should I replace it only if it's monobehaviours and check for that or just straight up replace ```0xFFFF``` with that for everything? I'm not too familiar with Unity.

Also, if you want, I can send the assets file to you if you'd think it would help.

**Comment by nesrak1** [comment]
> Should I replace it only if it's monobehaviours and check for that or just straight up replace 0xFFFF with that for everything? I'm not too familiar with Unity.

Monobehaviours are kind of a pain in unity because they are of the same type (MonoBehaviour 0x72) but they are unique because they use a second field called scriptIndex that differentiates different monobehaviours. Anything that isn't a monobehaviour is script index 0xFFFF and anything that is a monobehaviour has a different script index unique to each c# script. tldr, using `GetScriptIndex` is never a bad thing, but if you know you're not replacing any monobehaviours, you can use 0xFFFF as a shortcut.

> Also, if you want, I can send the assets file to you if you'd think it would help.

That will make debugging easier if you could.

**Comment by Skyluker4** [comment]
[Here you go](https://mega.nz/file/IR4ilSJQ#FmASMalCFwCE2LEGifjAvjiATA5t4pL7P9Pz6HQbxnc)

**Comment by nesrak1** [comment]
This is a bug with your program. Close the writer you use on the bundle file so that the bundle header can update.

**Comment by Skyluker4** [comment]
I couldn't get it to work with that. Is this the right way to do it? <https://github.com/Skyluker4/UnityAssetReplacer/tree/replace-fix>

**Comment by nesrak1** [comment]
Close the writer, not the reader.

**Comment by Skyluker4** [comment]
I see what you mean now. It works. Thank you! Do you know why it only messed up with this one specific file? Also, the documentation should probably be updated so no one else runs into this problem.

**Comment by nesrak1** [comment]
I would've honestly expected more to break, but I figure that the other bundles you edited only had one block instead of the three in this one.
