### ISSUE TITLE
Reading asset bundle from memory

### ISSUE THREAD

**Issue by Lombra** [nesrak1/AssetsTools.NET#41]
Hi,

Bit a of a newbie here. (especially when it comes to Unity assets) I have some asset bundles that are loaded into memory that I'm looking to read. They are of type `MonoBehaviour`, as I understand.

I think I can use the following to load the data, but I'm not sure where to go after that.
```
var bun = new AssetBundleFile();
bun.Read(new AssetsFileReader(memoryStream), true);
if (bun.bundleHeader6.GetCompressionType() != 0)
{
    bun = BundleHelper.UnpackBundle(bun);
}
```

**Comment by nesrak1** [comment]
Not sure what you are trying to read, but here's a bit of example code to read a few fields from a specific script.

```cs
var am = new AssetsManager();

//load bundle
var bunInst = am.LoadBundleFile(memoryStream);
//load the first file in bundle as an assets file
//note the first file may not be an assets file, so check
//bunInst.file.bundleInf6.dirInf[i].name if you're not sure
var inst = am.LoadAssetsFileFromBundle(bunInst, 0);

//loop over all monobehaviours in the assets file
foreach (var info in inst.table.GetAssetsOfType(0x72)) //0x72 = MonoBehaviour
{
    //load the monobehaviour data and get the first field
    AssetTypeValueField mbBaseField = am.GetTypeInstance(inst.file, info).GetBaseField();

    //filter out only monobehaviours of the name "MyScript"
    //the name can be found in the monoscript attached to this monobehaviour
    AssetTypeValueField m_Script = mbBaseField.Get("m_Script");
    AssetTypeValueField msBaseField = am.GetExtAsset(inst, m_Script).instance.GetBaseField();

    string m_ClassName = msBaseField.Get("m_ClassName").GetValue().AsString();

    //break if this isn't the script we're looking for
    if (m_ClassName != "MyScript")
    {
        break;
    }

    //now that we know we have the right monobehaviour, we can read it like normal
    float x = mbBaseField.Get("x").GetValue().AsFloat();
    float y = mbBaseField.Get("y").GetValue().AsFloat();
    Console.WriteLine($"position: {x},{y}");
}
```

**Comment by Lombra** [comment]
Hi,

To clarify, I don't have the data on file, only in memory, so I can't use a `FileStream`, which is what `LoadBundleFile` seems to require.

I tried doing this instead
```cs
var bunInst = new BundleFileInstance(memoryStream, "fileName", "");
```
but that gave me this error in `LoadAssetsFileFromBundle`.
> System.NullReferenceException: 'Object reference not set to an instance of an object.'
> 
> bunInst.file.bundleInf6.dirInf was null.

Taking the same memory stream and writing it to disk instead, and then opening it as a file instead, does work.

I don't know the proper terminology, but I'm looking to read the `mLanguages` and `mTerms` data from the `MonoBehaviour` section.

![bild](https://user-images.githubusercontent.com/8340020/123521183-7547da80-d6b5-11eb-9c3d-60a8aa78073e.png)

**Comment by nesrak1** [comment]
> To clarify, I don't have the data on file, only in memory, so I can't use a FileStream, which is what LoadBundleFile seems to require.

My mistake, this method is supposed to support regular streams. I just fixed this.

> but that gave me this error in LoadAssetsFileFromBundle.

Another bug, for whatever reason the stream variant wasn't decompressing the bundle.

> I don't know the proper terminology, but I'm looking to read the mLanguages and mTerms data from the MonoBehaviour section.

I can't tell what these types are from the screenshot since you didn't open the fields. If these were say, List\<string\> or such, you could do this to print each string item from the array.

```cs
var mLanguages = mbBaseField.Get("mLanguages");
foreach (var languageField in mLanguages.GetChildrenList())
{
    var languageString = languageField.GetValue().AsString();
    Console.WriteLine(languageString);
}
```

**Comment by Lombra** [comment]
That works now, thanks!

I've ended up with this:
```cs
var langIndex = -1;

var mLanguages = mbBaseField.Get("mLanguages");
for (var j = 0; j < mLanguages[0].childrenCount; j++) {
	if (mLanguages[0][j]["Code"].value.AsString() == "en") {
		langIndex = j;
		break;
	}
}

var mTerms = mbBaseField.Get("mTerms");
foreach (var term in mTerms[0].children) {
	locale.Add(term["Term"].value.AsString(), term["Languages"][0][langIndex].value.AsString());
}
```
It's a bit verbose with all the `.value` and `AsString()`, but it works.

Here is a sample of the types in question, for the record:

![bild](https://user-images.githubusercontent.com/8340020/123528663-6bd86580-d6e9-11eb-9ac3-1c4fef33f97f.png)

**Comment by nesrak1** [comment]
> It's a bit verbose with all the .value and AsString(), but it works.

Yeah, I get this quite a bit. It's exactly as it was in the original library, but I have considered moving the GetX methods to the field to skip .value
