### ISSUE TITLE
Problems with large asset bundles

### ISSUE THREAD

**Issue by nrgill28** [nesrak1/AssetsTools.NET#44]
I've been trying to use this library in one of my projects to modify asset bundles but I keep running into issues when using with large asset bundles. I'm basically just iterating over the MonoScript assets in the bundle and modifying the `m_AssemblyName` property on each one to point to a different assembly. It works well on smaller bundles but I run into issues on larger ones.

Notably that the library seems to use a LOT of memory when reading large files, many times more than the size of the decompressed bundle itself, but also that because of [this integer cast](https://github.com/nesrak1/AssetsTools.NET/blob/master/AssetTools.NET/Extra/BundleHelper.cs#L21) bundles with decompressed sizes over 2GB will also cause an integer overflow and fail to load entirely throwing an ArgumentOutOfBounds exception on the `ReadBytes()` call below.

I was hoping that the `BundleReplacerFromStream` and `AssetsReplacerFromStream` would allow me to perform my operations while keeping memory usage down but after trying and looking into it, it too just [reads the entire stream into another byte array](https://github.com/nesrak1/AssetsTools.NET/blob/master/AssetTools.NET/Standard/BundleReplacer/BundleReplacerFromStream.cs#L62-L65) and doesn't really solve much of anything.

I would like to continue using this library and I'll be experimenting seeing if I can find any workarounds, but I thought I'd open this just in case anyone had some useful info.

**Comment by nesrak1** [comment]
When this was being written, I didn't expect it to be used on bundles so large. ReadBytes, byte arrays, MemoryStream, etc. are all capped at 2gb and afaik the only solution is to use FileStream. Bundle unpack has already been changed to CopyTo() and ReplacerFromStream can be fixed as well. Bundle pack is going to be hard but I'll look into it.
As for BundleHelper, I can add a Stream variant with CopyTo(). But LoadAssetDataFromBundle loads a specific file from the bundle, and if you're only opening assets files they aren't usually 2gb. Usually that's only resS files.

**Comment by nrgill28** [comment]
Hey, so thought I'd give an update on this. After poking about, I can reduce the memory usage to effectively zero for my situation by just replacing the [`MemoryStream` used in BundleHelper.UnpackBundle](https://github.com/nesrak1/AssetsTools.NET/blob/master/AssetTools.NET/Extra/BundleHelper.cs#L82) with a `FileStream` to a temp file.

**Comment by nesrak1** [comment]
The method right under it `UnpackBundleToStream` should support FileStream already.

**Comment by nrgill28** [comment]
It does, however I don't actually call that method myself. I use the AssetsManager to load the bundle file and it doesn't give the option to choose which it uses.

[Here's my code, for reference.](https://github.com/H3VR-Modding/MeatKit/blob/main/Assets/MeatKit/Editor/BundleExporter.cs#L19)
