### ISSUE TITLE
how to get an asset's fields completely?

### ISSUE THREAD

**Issue by nopa607** [nesrak1/AssetsTools.NET#45]
hi, refering to the README document, i can get a asset's name easily using this script:
`            //Load assets file
            var am = new AssetsManager();
            var inst = am.LoadAssetsFile("C:\\Users\\Desktop\\UnityDemo_2018_3D_Data\\sharedassets0.assets", true);

            //Load class database
            am.LoadClassPackage("classdata.tpk");
            am.LoadClassDatabaseFromPackage(inst.file.typeTree.unityVersion);

            //Get asset info
            var table = inst.table;

            //foreach (var inf in inst.table.GetAssetsOfType((int)AssetClassID.GameObject))
            foreach (var inf in inst.table.GetAssetsOfType(150))
            {
                var baseField = am.GetTypeInstance(inst, inf).GetBaseField();

                var name = baseField.Get("m_Name").GetValue().AsString();
                Console.WriteLine(name);
            }`

but, i wonder how to get my asset's full field completly, just like this:
![image](https://user-images.githubusercontent.com/54985153/133882533-0ccd9604-45de-4506-a408-6f6f796e089a.png)

**Comment by nesrak1** [comment]
Not sure if you mean the components of a gameobject (which is what the window in assetsview shows) or just all the fields in an asset.

If you mean how to get the components, that's stored in the m_Component field, so you can do
```cs
//when baseField is from a GameObject
var arrayField = baseField.Get("m_Component").Get("Array");
for (var childField in arrayField.GetChildrenList())
{
    //blah blah do stuff with childField
}
```

If you mean how to just get all the fields instead of one specific one, use GetChildrenList
```cs
for (var childField in baseField.GetChildrenList())
{
    //blah blah do stuff with childField
}
```

You are looping all assets of type 150 (PreloadData) so I assume the latter.

**Comment by nopa607** [comment]
thanks, i resolved it;
its a great tool! could u share the reason why u decided to program AssetsTools? because i found AssetStudio before i found you, and AssetsStudio actually has some weakness(eg : it cannot loadding ParticalSystem) and you make it !

**Comment by nesrak1** [comment]
AssetsTools.NET is just a c# version of AssetsTools (c++). I needed to read MonoBehaviours and I didn't want to deal with debugging a closed source native library when things went wrong.
