### ISSUE TITLE
AssetsView "Properties" context menu item crashes the application

### ISSUE THREAD

**Issue by arcusmaximus** [nesrak1/AssetsTools.NET#47]
If I rightclick any item in AssetsView and choose Properties, the application crashes. The cause is an ArgumentOutOfRangeException that gets thrown at the following line in StartScreen.cs:

```
ushort monoId = currentFile.file.typeTree.unity5Types[info.curFileTypeOrIndex].scriptIndex;
```

`curFileTypeOrIndex` is (for example) 115, but `unity5Types` has only 9 items.

The assets file I opened has version number 5.1.4f1.

**Comment by nesrak1** [comment]
This code most likely predates pre unity 5.5 support, this should actually be using `GetScriptIndex()`. Fixed in latest commit.
