### ISSUE TITLE
System.NullReferenceException: 'Object reference not set to an instance of an object.'

### ISSUE THREAD

**Issue by kiletw** [nesrak1/AssetsTools.NET#50]
u5Type is null.

![image](https://user-images.githubusercontent.com/18109554/136675913-23f7dadf-d9c1-4a65-a532-a2c8d5ba9ac8.png)

![image](https://user-images.githubusercontent.com/18109554/136675922-bd52c5d1-7a10-4fa6-9f11-faaed4d1e5f8.png)

unity version 5.3.3f1
Error file
[ResDATA_DIALOGBG_dialog_dialog212.zip](https://github.com/nesrak1/AssetsTools.NET/files/7316541/ResDATA_DIALOGBG_dialog_dialog212.zip)

**Comment by nesrak1** [comment]
Should be fixed in latest commits, support for 5.4 and below is not very good right now since I don't mod any games that old.

**Comment by kiletw** [comment]
is work.
