### ISSUE TITLE
Here's a Better Fix for Loading ClassDatabseFile from Package

### ISSUE THREAD

**Issue by wh0am15533** [nesrak1/AssetsTools.NET#56]
I notice that AssetsTools.NET will throw error's if the am.classFile is null or if a wrong one is loaded, and your code will select a Unity 5.x version because of how the list is ordered, so that is definately going to cause issues if using a new Unity version, like getting the type instance or basefield.. So short of as you said a version selector, here is a modification to your code that will find the closest matching Unity version if the game version doesn't exist in the tpk. (It helps alot, but some Unity versions still may not work correctly if it's not in the tpk) Note: You will also notice a significant performance increase in parsing resource's You can test it with 'Mist Legacy' from steam, there's no TypeDump for the Unity version (2020.3.20f1) yet but x.18f1 exists which should be your result:

```am.LoadClassDatabaseFromPackage(inst.file.typeTree.unityVersion, true);
if (am.classFile == null)
{
	int index = am.classPackage.header.files.FindIndex(f => f.name.StartsWith("U" + inst.file.typeTree.unityVersion));
	if (index >= 0) // -1 mean's it isn't in current tpk
	{
		am.classFile = am.classPackage.files[index]; // If am.classFile is Null you get errors.
	}
	else
	{
		List<ClassDatabaseFile> files = am.classPackage.files;

		// Filter all classDbFiles for matching versions
		var unityMajMinVer = inst.file.typeTree.unityVersion.Substring(0, 6);
		var filter1 = files.Where(f => f.header.unityVersions[0].StartsWith(unityMajMinVer)).OrderBy(v => v.header.unityVersions[v.header.unityVersionCount - 1]);
		var filter2 = filter1.Where(f => f.header.unityVersions[f.header.unityVersionCount - 1].Trim().Length == inst.file.typeTree.unityVersion.Length).OrderBy(v => v.header.unityVersions[v.header.unityVersionCount - 1]);

		// Get the SubMinor version number
		string unitySubMinVer = inst.file.typeTree.unityVersion.Split('.')[2];
		string tmpNum = "";
		if (unitySubMinVer.Length >= 4) { tmpNum = unitySubMinVer.Substring(0, 2); } else { tmpNum = unitySubMinVer.Substring(0, 1); }

		// Make Existing Num List 
		List<int> nums = new List<int>();
		foreach (var pos in filter2) { nums.Add(int.Parse(pos.header.unityVersions[pos.header.unityVersionCount - 1].Split('.')[2].Substring(0, tmpNum.Length))); }
		int closest = nums.Aggregate((x, y) => Math.Abs(x - int.Parse(tmpNum)) < Math.Abs(y - int.Parse(tmpNum)) ? x : y);

		ClassDatabaseFile result = filter2.Where(f => f.header.unityVersions[f.header.unityVersionCount - 1].StartsWith(unityMajMinVer + "." + closest)).Single();
		am.classFile = result;

		//ORIG:
		//List<ClassDatabaseFile> files = tmpam.classPackage.files;
		//tmpam.classFile = files[files.Count - 1]; // will be Unity 5.x, due to order of list
	}
}
```

**Comment by nesrak1** [comment]
Could you make a pr for this? I'll review it when I have the time.

> there's no TypeDump for the Unity version (2020.3.20f1) yet

Here's a tpk that has 2020.3:
https://github.com/nesrak1/UABEA/raw/master/ReleaseFiles/classdata.tpk

[I'm planning on replacing UABE's class database with one fully generated from TypeTreeDumper.](https://github.com/nesrak1/TypeTreeDumpToTpk) Issue is that UABE's method of loading databases is loading every single one on startup, which eats up a lot of memory when every single version so far is loaded at once instead of just a few. If I make it only load one at a time then it breaks saving. So I'm not sure what I'll do with that yet.

**Comment by wh0am15533** [comment]
Thanks for the heads up and tpk. I can generate the tpk's on the fly at runtime, however I do have the same issue you face, plus they add the 4 terminator bytes to every name so searching is a bitch. I think I got alot of new stuff for you for I guess AssetHelper. Yeah, that tpk load time is timely... also the saving, I making some improvement's that I'll pass along to you. I been playing with your tpk repo and made alot of advancement's, great project BTW. This is a great library and if I can improve I will. Thnx.
