### ISSUE TITLE
Fix bundle repacking in-memory

### ISSUE THREAD

**Issue by nesrak1** [nesrak1/AssetsTools.NET#57]
Bundles right now are being compressed directly in memory. This is because it needs to be placed after a compressed table which is dependent on the compressed data after it, and the compressed table can change in size depending on how the compressed data is compressed. Both Unity and DevX compress in a temporary file and copy over later, UnityPy writes directly in memory (what we're doing), and UABE sets the "table at end of file" flag (0x80).

* Writing in a temporary file
  * I don't like this method particularly because the input into Pack method is a stream. If the stream is a MemoryStream, how do we decide where to place temporary files (or just put them in %temp% or something?). This requires making a temporary file with the compressed data and copying the data into the final file later, so you end up with two copies of the data on the disk.
* Using written file as a temporary file and move the bytes
  * Basically just write the table uncompressed up front, write the compress data after it, compress and overwrite the original table, and reposition the compressed bytes. Prevents us from using a temporary file but still requires double writing.
* Writing in memory
  * Obviously not good for large bundles, but easiest to do. MemoryStreams are limited to 2GB, but apparently we can make a custom MemoryStream to support more than 2GB. I don't like this idea but it's possible.
* Use table at end of file flag
  * Easiest option, just set the flag and write table at the end. The editor never uses this itself, so you'll never see this from any built game afaik. I don't know if this will stick around or not.

I think the table at end of file flag is probably the best decision, but it produces bundles with a flag that isn't used normally and can be easily identified as being created by AssetsTools(.NET).

**Comment by binn** [comment]
Within the .NET ecosystem, using temporary files is a recommended pattern. The `Path.GetTempFileName` method exists for this purpose (and is cross-compatible)

> Use table at end of file flag
> Easiest option, just set the flag and write table at the end. The editor never uses this itself, so you'll never see this from any > > built game afaik. I don't know if this will stick around or not.

While this works, this would essentially result in a file being created outside of the norm (it would be pretty easy to detect "Hey this was made by AssetsTools.NET); which if people are using the library for game modification then games could crack down on them. (unless that's not a goal you want ATN to obtain)

> Using written file as a temporary file and move the bytes
Basically just write the table uncompressed up front, write the compress data after it, compress and overwrite the original table, and reposition the compressed bytes. Prevents us from using a temporary file but still requires double writing.

This also isn't so bad either.

> Writing in memory
Obviously not good for large bundles, but easiest to do. MemoryStreams are limited to 2GB, but apparently we can make a custom MemoryStream to support more than 2GB. I don't like this idea but it's possible.

This unfortunately puts a hard limit and requires much beefier hardware than a simple temporary file. The performance of all options undermines this one, but it would be relatively simple to turn it into an interface and let people choose the decompression/compression strategy themselves. `IAssetPacker.Pack(wr, wr, lzma);`, e.g. `IAssetPacker packer = new TemporaryFileStrategyAssetPacker();`

**Comment by binn** [comment]
Optionally allowing support for .NET's async/await (and in general, asynchronous compression/decompression), letting people set up progress bars or collect progress analytics. (Couldn't find anything built-in yet). My use case is almost solely just compressing asset bundles in a set of batch containers performing nightly jobs.

**Comment by nesrak1** [comment]
> Optionally allowing support for .NET's async/await (and in general, asynchronous compression/decompression)

Agree, although I'm not sure if we can keep compatibility with .net 3.5 if this were added.

> letting people set up progress bars or collect progress analytics

This has been requested quite a bit. LZMA compressor has an interface to check progress, but if I recall the LZ4 compressor doesn't.

**Comment by binn** [comment]
I'm not sure if the Path.GetTempFileName is available in .NET 3.5, but preprocessor directives could be used to target .NET 3.5 and .NET Core/.NET moving forward. Although I don't see a reason to stay compatible with .NET 3.5 other than Unity's dependency on it (my assumption is that the library is being used outside of unity, VS doesn't let you download older than 4.7.2 by default, and .NET Core 2 and below downloads are hidden in the array of MS downloads)

> This has been requested quite a bit. LZMA compressor has an interface to check progress, but if I recall the LZ4 compressor doesn't.

If possible, the entire compression strategies could be interfaces, allowing people to implement their own bindings/versions of LZMA/LZ4 (e.g. relying on a platform-specific native API (linux), instead of using SevenZipSharp).

> Agree, although I'm not sure if we can keep compatibility with .net 3.5 if this were added.

A lot of libraries tend to target both patterns with a 
`file.PackAsync();` and `file.Pack();` system of methods, whereas on .NET 3.5 the `PackAsync` method wouldn't be available due preprocessor directives.

**Comment by nesrak1** [comment]
> Although I don't see a reason to stay compatible with .NET 3.5 other than Unity's dependency on it

Yeah that's the reason, there are some projects that use AssetsTools.NET in the editor or in game.

> For the sake of better code understanding, would it be possible to add xmldoc commenting to everything?

That's the plan. I just haven't gotten to it yet.

**Comment by nesrak1** [comment]
https://github.com/nesrak1/AssetsTools.NET/tree/bundle-writing-temp-file
New branch created to write assets files to temp files. Still need to do more testing, but seems to be working for now.

**Comment by nesrak1** [comment]
Latest version uses `Writing in a temporary file` and `Use table at end of file flag` which can be toggled by a new flag. By default it uses `Use table at end of file flag` to true but this can be turned off if needed.
