### ISSUE TITLE
CI builds

### ISSUE THREAD

**Issue by slash-under** [nesrak1/AssetsTools.NET#73]
Transparent CI builds would be an important improvement, depending on the platform, I can send a PR that adds this feature.

**Comment by nesrak1** [comment]
I've been meaning to do this, but if you want to make a PR right now I won't be opposed.

**Comment by slash-under** [comment]
Do you have a preference as to where it runs? Github Actions is usually the simplest, in my experience.

**Comment by nesrak1** [comment]
Yes, use GitHub Actions.

**Comment by slash-under** [comment]
Sent over an initial implementation
