### ISSUE TITLE
when disable write typetree, am.LoadAssetsFileFromBundle returns null

### ISSUE THREAD

**Issue by liangyi-2013** [nesrak1/AssetsTools.NET#76]
If I use the code below to build bundles 
``` C#
BuildPipeline.BuildAssetBundles(dir, BuildAssetBundleOptions.DisableWriteTypeTree, BuildTarget.WebGL);
```
and use the code below to read a bundle. am.LoadAssetsFileFromBundle always returns null.
```C#
            var am = new AssetsManager();

            am.LoadClassPackage("classdata.tpk");

            var bun = am.LoadBundleFile("file/bg_11zhuan1.bundle");
            var inst = am.LoadAssetsFileFromBundle(bun, bun.file.GetFileName(0));

```
If I use BuildAssetBundleOptions.None instead of  BuildAssetBundleOptions.DisableWriteTypeTree to build bundles, am.LoadAssetsFileFromBundle doesn't return null.
What should I do I, if I want to use BuildAssetBundleOptions.DisableWriteTypeTree?

**Comment by liangyi-2013** [comment]
You can use this [bundle](https://in-rxjh-cdnres.me4399.com/CN/stable/up/wechat_cn_rel_164015/bg_11zhuan1.ab) to test.

**Comment by nesrak1** [comment]
> You can use this [bundle](https://in-rxjh-cdnres.me4399.com/CN/stable/up/wechat_cn_rel_164015/bg_11zhuan1.ab) to test.

The code that checks whether a file is an assets file expects the version string to not contain any special characters. In your case, you have a custom engine string ending with \n2 (common for custom engine versions) that causes this check to fail. Since this is fairly common, I don't mind adding this to the regex.

**Comment by liangyi-2013** [comment]
It works,Thanks very much!
