### ISSUE TITLE
Modifying of Unity 5.6.5 assets

### ISSUE THREAD

**Issue by wasikuss** [nesrak1/AssetsTools.NET#77]
I've issues with modifying assets of the game based on Unity 5.6.5. Already found that using `AssetsReplacer` with no changes at all crashes game.

I've done 2 tests. First, `AssetsFileWriter` without any `AssetsReplacer` doesn't change anything. Second, adding `AssetsReplacerFromMemory` with `changedBytes` (`baseField.WriteToByteArray()`) without doing any modifications completely changes whole file and makes game crash.

I'm using `AssetsTools.NET v2.0.11`.

**Comment by nesrak1** [comment]
What asset type? Monobehaviour?

**Comment by wasikuss** [comment]
Mesh. I've wanted to replace one mesh using another from the same asset as a test. Doing it manually via UABE works fine.
[replace.zip](https://github.com/nesrak1/AssetsTools.NET/files/8524760/replace.zip)

**Comment by nesrak1** [comment]
Can you set `monoScriptIndex` in the `AssetsReplacerFromMemory` constructor to 0xffff instead of 0?

**Comment by wasikuss** [comment]
Yes, now it's working. Till fix, I'll be using 0 or 0xffff depending on which value won't crash the game. Thanks!

**Comment by nesrak1** [comment]
It's not something that needs a "fix". When you set this value, you directly set a value in the assets file which tells Unity to look for a monoscript which doesn't exist.

From the readme:

> The constructor for AssetsReplacers take a monoScriptIndex parameter. If you won't be touching MonoBehaviour assets, leave this as 0xffff like in this example (no script id) as a shortcut. If you are editing MonoBehaviours, use AssetHelper.GetScriptIndex() to get the correct script index. More information about this in the MonoBehaviour reading/writing section.

**Comment by wasikuss** [comment]
True, my bad. Somehow on newer versions of Unity `0` was fine. More convenient would be to add another constructor with that param to be last and the default set to `0xffff` like in `AssetsRemover`. Thanks!
