### ISSUE TITLE
Inconsistencies in LZMA compression between different tools

### ISSUE THREAD

**Issue by katboi01** [nesrak1/AssetsTools.NET#80]
![image](https://user-images.githubusercontent.com/59540382/182113824-fd563fab-92e9-4982-bb4f-443e03916a4e.png)
When trying to extract files compressed with LZMA (created using UABE 2.2), this error shows up. I compared lzmaDecoder.cs with the one from Perfare's AssetStudio and they are the same, so the issue lies elsewhere. Any help getting it to extract the files would be appreciated.
I uploaded two example files here, one which works and one which doesn't.
https://anonfiles.com/a7W0E61bya/model_LZMA
https://anonfiles.com/c8WaEd1cy8/model_LZ4

**Comment by nesrak1** [comment]
I think your file just compressed bad. Opening it with UABE 3.0 fails as well.

**Comment by katboi01** [comment]
Thank you for responding to my issue. I have already reported lack of compression functionality in UABE 3.0+ and the developer admitted to have overlooked it (https://github.com/SeriousCache/UABE/issues/482). The files were created in version 2.2 stable d, and can be opened by it. They are also supported in most recent AssetStudio.
Additionally, I compressed a file using yours AssetsTools.Net, with compression set to LZMA, and the file is not supported by AssetStudio, but can be opened by AssetView and UABE 3.0+. (https://anonfiles.com/mds7H21cyc/example_LZMA_UABEA)

From what I gather, there are currently 2 versions of the LZMA format - one which works in AssetStudio and old UABE, and one which works with UABEA and UABE 3.0+. I would be very grateful if you could look into it and see if support for the other version is possible, but I understand if that's not something you want to add.

**Comment by nesrak1** [comment]
That's odd that two programs can't read the different formats considering I originally tested AssetsTools.NET's compression on UABE 2.2 and AssetStudio. From my limited debugging, it looks like it reads from the correct location but the LZMA decompressor looks like it's expecting more data than there is in the file. Maybe I'll open AS in a debugger to see what it does.

**Comment by katboi01** [comment]
I'm sorry, I forgot to check it, but files created with AssetsTools.Net also work with the old 2.2d version of UABE, but it doesn't work the other way around, files created in 2.2d don't work in AssetView

**Comment by nesrak1** [comment]
I've updated both master and the version 3 branch as well as the UABEA at3 branch with the fix for loading compressed bundles. Turns out it was a really old issue that I only fixed in one place but not another.

As for compressing bundles not loading in AssetStudio, I'm not having that issue. If I compress with UABEA and open in AssetStudio it seems to work without issues.

**Comment by katboi01** [comment]
Thank you! I confirm that reading files is now working correctly, which is what I was after. The issue can be closed.

The compression problem I have could be an issue of my workflow, and is not something that I'm planning to use, so I will not mention it further, unless you want me to investigate it. In short, reading a LZ4 file, making changes, and saving it at LZMA made it unreadable for AssetStudio. Doing it again with the output LZMA file as input makes it work again. It could be that I don't clear some data between reading and saving the file.

**Comment by nesrak1** [comment]
Cool, going to close now
