### ISSUE TITLE
Where to get *TPK / CLDB files

### ISSUE THREAD

**Issue by cnSchwarzer** [nesrak1/AssetsTools.NET#95]
3.0 uses these files and dropped support for old format, but I found nowhere to download these files.

**Comment by nesrak1** [comment]
Solved in discord. Link is at https://github.com/AssetRipper/Tpk/actions/workflows/make_tpk.yml which is mentioned on the wiki page here: https://github.com/nesrak1/AssetsTools.NET/wiki/Getting-Started:-Assets-file-reading
